xcodeproj 'MMAPreferencePane.xcworkspace/MMAPP.xcodeproj'
workspace 'MMAPreferencePane'

pod 'YOLOKit/flatten'
pod 'YOLOKit/has'
pod 'YOLOKit/join'
pod 'YOLOKit/map'
pod 'YOLOKit/none'
pod 'YOLOKit/select'
pod 'YOLOKit/skip'
pod 'YOLOKit/split'
pod 'PromiseKit/Promise'
pod 'PromiseKit/When'
pod 'PromiseKit/NSTask'
pod 'PromiseKit/NSURLConnection'
pod 'ChuzzleKit'
pod 'sym0'
