xcodeproj 'MMAPreferencePane.xcworkspace/MMAPP.xcodeproj'
workspace 'MMAPreferencePane'

pod 'YOLOKit/flatten'
pod 'YOLOKit/has'
pod 'YOLOKit/join'
pod 'YOLOKit/map'
pod 'YOLOKit/skip'
pod 'YOLOKit/split'
pod 'PromiseKit/Promise'
pod 'PromiseKit/When'
pod 'ChuzzleKit'
